<x-admin-layout title="Seller Applications">
<div class="mx-auto max-w-[1400px] px-5 py-8 md:px-8 lg:py-10">
 <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h1 class="text-3xl font-extrabold tracking-tight md:text-4xl">Seller Applications</h1><p class="mt-2 text-[#626576]">Review creator profiles before granting seller access.</p></div><span class="rounded-full bg-amber-50 px-4 py-2 text-sm font-semibold text-amber-800">{{ $sellers->total() }} pending</span></div>
 <div class="mt-8 grid gap-5 xl:grid-cols-2">@forelse($sellers as $profile)
  <article class="flex flex-col rounded-xl border border-[#d7d9e5] bg-white p-6 shadow-sm"><div class="flex items-start gap-4"><span class="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-[#e9e7ff] text-lg font-bold text-[#3525cd]">{{ str($profile->display_name)->substr(0,1)->upper() }}</span><div class="min-w-0"><h2 class="truncate text-xl font-bold">{{ $profile->display_name }}</h2><p class="text-sm text-[#3525cd]">{{ '@'.$profile->username }}</p></div><span class="ml-auto rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-800">Pending</span></div><div class="mt-5 grid gap-3 text-sm sm:grid-cols-2"><div><p class="text-xs uppercase tracking-wide text-[#777a8a]">Full legal name</p><p class="mt-1 font-medium">{{ $profile->full_name ?? '—' }}</p><p class="truncate text-[#626576]">{{ $profile->user->email }}</p></div><div><p class="text-xs uppercase tracking-wide text-[#777a8a]">Business name</p><p class="mt-1 font-medium">{{ $profile->business_name ?? '—' }}</p>@if($profile->website)<a href="{{ $profile->website }}" rel="noopener" target="_blank" class="truncate text-[#3525cd] hover:underline">{{ $profile->website }}</a>@endif</div><div class="sm:col-span-2"><p class="text-xs uppercase tracking-wide text-[#777a8a]">Verification address</p><p class="mt-1 font-medium">{{ collect([$profile->address,$profile->city,$profile->postal_code,$profile->country])->filter()->join(', ') ?: '—' }}</p>@if($profile->phone)<p class="text-[#626576]">{{ $profile->phone }}</p>@endif</div></div><p class="mt-5 flex-1 rounded-lg bg-[#f6f7fb] p-4 text-sm leading-6 text-[#525565]">{{ $profile->biography }}</p><div class="mt-5 grid gap-3 sm:grid-cols-[auto_1fr]"><form method="POST" action="{{ route('admin.sellers.approve',$profile) }}">@csrf<button class="w-full rounded-lg bg-emerald-600 px-5 py-2.5 text-sm font-semibold text-white">Approve seller</button></form><form method="POST" action="{{ route('admin.sellers.reject',$profile) }}" class="flex gap-2">@csrf<input name="reason" required placeholder="Reason for rejection" class="min-w-0 flex-1 rounded-lg border border-[#d7d9e5] px-3 py-2 text-sm"><button class="rounded-lg border border-red-200 px-4 py-2 text-sm font-semibold text-red-700 hover:bg-red-50">Reject</button></form></div></article>
 @empty<div class="col-span-full rounded-xl border border-[#d7d9e5] bg-white px-6 py-16 text-center text-[#626576]"><span class="material-symbols-outlined mb-3 block text-5xl text-emerald-600">verified_user</span><h2 class="font-bold text-[#111827]">Applications are up to date</h2><p class="mt-1 text-sm">No seller applications are waiting for review.</p></div>@endforelse</div><div class="mt-6">{{ $sellers->links() }}</div>

 <div class="mt-12">
  <div class="flex items-center justify-between"><h2 class="text-2xl font-extrabold tracking-tight">Approved authors</h2><span class="rounded-full bg-emerald-50 px-4 py-2 text-sm font-semibold text-emerald-800">{{ $approved->where('is_featured',true)->count() }} featured</span></div>
  <p class="mt-1 text-sm text-[#626576]">Feature standout authors to badge their storefront and surface their work.</p>
  <div class="mt-5 overflow-hidden rounded-xl border border-[#d7d9e5] bg-white shadow-sm">
   <div class="overflow-x-auto"><table class="w-full min-w-[720px] text-left text-sm">
    <thead class="bg-[#edf2ff] text-xs uppercase tracking-[.08em] text-[#424555]"><tr><th class="px-5 py-4">Author</th><th class="px-5 py-4">Business</th><th class="px-5 py-4">Country</th><th class="px-5 py-4">Status</th><th class="px-5 py-4 text-right">Featured</th></tr></thead>
    <tbody class="divide-y divide-[#e2e4ec]">
    @forelse($approved as $profile)
     <tr class="hover:bg-[#fafbff]">
      <td class="px-5 py-4"><div class="flex items-center gap-3"><span class="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#e9e7ff] text-sm font-bold text-[#3525cd]">{{ str($profile->display_name)->substr(0,1)->upper() }}</span><div><a href="{{ route('sellers.show',$profile->username) }}" target="_blank" rel="noopener" class="font-semibold text-[#251bd5] hover:underline">{{ $profile->display_name }}</a><p class="text-xs text-[#777a8a]">{{ '@'.$profile->username }}</p></div></div></td>
      <td class="px-5 py-4 text-[#626576]">{{ $profile->business_name ?? '—' }}</td>
      <td class="px-5 py-4 text-[#626576]">{{ $profile->country ?? '—' }}</td>
      <td class="px-5 py-4">@if($profile->is_featured)<span class="rounded-full bg-[#3525cd] px-3 py-1 text-xs font-bold text-white">Featured</span>@else<span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">Standard</span>@endif</td>
      <td class="px-5 py-4 text-right"><form method="POST" action="{{ route('admin.sellers.feature',$profile) }}">@csrf @method('PUT')<button class="rounded-lg border px-4 py-1.5 text-xs font-semibold {{ $profile->is_featured ? 'border-[#d7d9e5] text-[#555868] hover:bg-[#f4f6fd]' : 'border-[#3525cd] text-[#3525cd] hover:bg-[#3525cd]/10' }}">{{ $profile->is_featured ? 'Unfeature' : 'Feature' }}</button></form></td>
     </tr>
    @empty<tr><td colspan="5" class="px-6 py-12 text-center text-[#777a8a]">No approved authors yet.</td></tr>@endforelse
    </tbody>
   </table></div>
  </div>
 </div>
</div></x-admin-layout>
