<?php
namespace App\Services;
use App\Enums\ProductStatus;
use App\Enums\ProductVersionStatus;
use App\Models\AuditLog;
use App\Models\Product;
use App\Models\User;
use Illuminate\Support\Facades\DB;
class ProductSubmissionService
{
 public function submit(Product $product,User $seller): void { $this->assertWithinListingLimit($product,$seller);DB::transaction(function()use($product,$seller){$product->update(['status'=>ProductStatus::Submitted,'submitted_at'=>now()]);$product->versions()->update(['status'=>ProductVersionStatus::PendingReview]);$product->reviewSubmissions()->create(['submitted_by'=>$seller->id,'status'=>'submitted','submitted_at'=>now()]);});app(AdminNotifier::class)->notify('review','Product submitted for review: '.$product->title,route('admin.products.review')); }
 /** Block a new listing from entering review once the seller's plan cap is reached. Resubmissions of already-counted listings are unaffected. */
 private function assertWithinListingLimit(Product $product,User $seller): void { $subscriptions=app(\App\Services\SubscriptionService::class);$limit=$subscriptions->listingLimitFor($seller);if($limit===null)return;$notYetCounted=in_array($product->status->value,['draft','rejected'],true);if($notYetCounted&&$subscriptions->activeListingCount($seller)>=$limit)abort(422,'Your current plan allows up to '.$limit.' active listings. Upgrade your plan to publish more.'); }
 public function approve(Product $product,User $admin,string $notes=''): void { DB::transaction(function()use($product,$admin,$notes){$old=$product->status->value;$product->update(['status'=>ProductStatus::Published,'published_at'=>now()]);$product->versions()->update(['status'=>ProductVersionStatus::Published,'published_at'=>now()]);$product->reviewSubmissions()->latest()->firstOrFail()->update(['reviewed_by'=>$admin->id,'status'=>'approved','review_notes'=>$notes,'reviewed_at'=>now()]);AuditLog::create(['user_id'=>$admin->id,'action'=>'product.approved','entity_type'=>Product::class,'entity_id'=>$product->id,'old_values'=>['status'=>$old],'new_values'=>['status'=>'published'],'ip_address'=>request()->ip(),'user_agent'=>request()->userAgent()]);});\Illuminate\Support\Facades\Cache::forget(\App\Http\Controllers\HomeController::CACHE_KEY);app(MarketplaceMailer::class)->productReviewed($product,'approved',$notes); }
 public function approveVersion(\App\Models\ProductVersion $version,User $admin,string $notes=''): void { DB::transaction(function()use($version,$admin,$notes){$version=\App\Models\ProductVersion::lockForUpdate()->findOrFail($version->id);if($version->status!==ProductVersionStatus::PendingReview)return;$version->update(['status'=>ProductVersionStatus::Published,'published_at'=>now()]);AuditLog::create(['user_id'=>$admin->id,'action'=>'version.approved','entity_type'=>\App\Models\ProductVersion::class,'entity_id'=>$version->id,'old_values'=>['status'=>'pending_review'],'new_values'=>['status'=>'published','notes'=>$notes],'ip_address'=>request()->ip(),'user_agent'=>request()->userAgent()]);}); }
 public function rejectVersion(\App\Models\ProductVersion $version,User $admin,string $notes): void { DB::transaction(function()use($version,$admin,$notes){$version=\App\Models\ProductVersion::lockForUpdate()->findOrFail($version->id);if($version->status!==ProductVersionStatus::PendingReview)return;$version->update(['status'=>ProductVersionStatus::Rejected]);AuditLog::create(['user_id'=>$admin->id,'action'=>'version.rejected','entity_type'=>\App\Models\ProductVersion::class,'entity_id'=>$version->id,'old_values'=>['status'=>'pending_review'],'new_values'=>['status'=>'rejected','notes'=>$notes],'ip_address'=>request()->ip(),'user_agent'=>request()->userAgent()]);}); }
 public function requestChanges(Product $product,User $admin,string $notes): void { DB::transaction(function()use($product,$admin,$notes){$old=$product->status->value;$product->update(['status'=>ProductStatus::ChangesRequested]);$product->versions()->where('status',ProductVersionStatus::PendingReview)->update(['status'=>ProductVersionStatus::Draft]);$product->reviewSubmissions()->latest()->firstOrFail()->update(['reviewed_by'=>$admin->id,'status'=>'changes_requested','review_notes'=>$notes,'reviewed_at'=>now()]);AuditLog::create(['user_id'=>$admin->id,'action'=>'product.changes_requested','entity_type'=>Product::class,'entity_id'=>$product->id,'old_values'=>['status'=>$old],'new_values'=>['status'=>'changes_requested','notes'=>$notes],'ip_address'=>request()->ip(),'user_agent'=>request()->userAgent()]);});app(MarketplaceMailer::class)->productReviewed($product,'changes_requested',$notes); }
}