<?php
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MarketplaceProductController;
use App\Http\Controllers\SellerApplicationController;
use App\Http\Controllers\SellerProductController;
use App\Http\Controllers\Admin\ProductReviewController;
use App\Http\Controllers\Admin\SellerReviewController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\SellerStorefrontController;
use App\Http\Controllers\SellerFollowController;
use App\Http\Controllers\SitemapController;
use App\Http\Controllers\WishlistController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\DownloadController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\StripeWebhookController;
use App\Http\Controllers\SellerFinanceController;
use App\Http\Controllers\StripeConnectController;
use App\Http\Controllers\WithdrawalController;
use App\Http\Controllers\Admin\WithdrawalReviewController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\SupportTicketController;
use App\Http\Controllers\RefundRequestController;
use App\Http\Controllers\NotificationPreferenceController;
use App\Http\Controllers\Admin\RefundReviewController;
use Illuminate\Support\Facades\Route;
Route::get('/', HomeController::class)->name('home');
Route::get('/products', [MarketplaceProductController::class, 'index'])->name('products.index');
Route::get('/products/{slug}', [MarketplaceProductController::class, 'show'])->name('products.show');
Route::get('/categories/{slug}', [CategoryController::class, 'show'])->name('categories.show');
Route::get('/authors/{username}', [SellerStorefrontController::class, 'show'])->name('sellers.show');
Route::get('/sitemap.xml', SitemapController::class)->name('sitemap');
Route::post('/stripe/webhook', StripeWebhookController::class)->name('stripe.webhook');
Route::middleware('guest')->group(function () {
    Route::view('/login', 'auth.login')->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store'])->middleware('throttle:login')->name('login.store');
    Route::view('/register', 'auth.register')->name('register');
    Route::post('/register', [RegisteredUserController::class, 'store'])->middleware('throttle:6,1')->name('register.store');
});
Route::middleware('auth')->group(function () {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
    Route::view('/admin', 'admin.dashboard')->middleware('role:administrator')->name('admin.dashboard');
    Route::get('/wishlist', [WishlistController::class, 'index'])->name('wishlist.index');
    Route::post('/wishlist/{product}', [WishlistController::class, 'toggle'])->name('wishlist.toggle');
    Route::post('/authors/{sellerProfile}/follow', [SellerFollowController::class, 'toggle'])->name('sellers.follow');
    Route::get('/cart', [CartController::class, 'index'])->name('cart.index');
    Route::post('/cart/{product}', [CartController::class, 'add'])->name('cart.add');
    Route::delete('/cart/items/{item}', [CartController::class, 'remove'])->name('cart.remove');
    Route::post('/checkout', [CheckoutController::class, 'store'])->name('checkout.store');
    Route::get('/checkout/{order}/success', [CheckoutController::class, 'success'])->name('checkout.success');
    Route::get('/purchases', [PurchaseController::class, 'index'])->name('purchases.index');
    Route::get('/purchases/{order}', [PurchaseController::class, 'show'])->name('purchases.show');
    Route::get('/downloads/{license}', DownloadController::class)->name('downloads.show');
    Route::post('/reviews/{orderItem}', [ReviewController::class, 'store'])->name('reviews.store');
    Route::post('/products/{product}/comments', [CommentController::class, 'store'])->name('comments.store');
    Route::get('/support', [SupportTicketController::class, 'index'])->name('support.index');
    Route::post('/support/{license}', [SupportTicketController::class, 'store'])->name('support.store');
    Route::get('/support/{supportTicket}', [SupportTicketController::class, 'show'])->name('support.show');
    Route::post('/support/{supportTicket}/reply', [SupportTicketController::class, 'reply'])->name('support.reply');
    Route::post('/refunds/{orderItem}', [RefundRequestController::class, 'store'])->name('refunds.store');
    Route::get('/notification-preferences', [NotificationPreferenceController::class, 'edit'])->name('notifications.preferences');
    Route::put('/notification-preferences', [NotificationPreferenceController::class, 'update'])->name('notifications.preferences.update');
    Route::get('/sell/apply', [SellerApplicationController::class, 'create'])->name('seller.apply');
    Route::post('/sell/apply', [SellerApplicationController::class, 'store'])->name('seller.apply.store');
    Route::middleware('role:seller')->prefix('seller')->name('seller.')->group(function () {
        Route::get('/finance', SellerFinanceController::class)->name('finance');
        Route::post('/withdrawals', [WithdrawalController::class, 'store'])->name('withdrawals.store');
        Route::get('/stripe-connect', [StripeConnectController::class, 'start'])->name('connect.start');
        Route::get('/stripe-connect/return', [StripeConnectController::class, 'returned'])->name('connect.return');
        Route::get('/stripe-connect/refresh', [StripeConnectController::class, 'refresh'])->name('connect.refresh');
        Route::get('/products', [SellerProductController::class, 'index'])->name('products.index');
        Route::get('/products/create', [SellerProductController::class, 'create'])->name('products.create');
        Route::post('/products', [SellerProductController::class, 'store'])->name('products.store');
        Route::post('/products/{product}/submit', [SellerProductController::class, 'submit'])->name('products.submit');
    });
    Route::middleware('role:administrator')->prefix('admin')->name('admin.')->group(function () {
        Route::post('/withdrawals/{withdrawalRequest}/reject', [WithdrawalReviewController::class, 'reject'])->name('withdrawals.reject');
        Route::post('/refunds/{refundRequest}/approve', [RefundReviewController::class, 'approve'])->name('refunds.approve');
        Route::post('/sellers/{sellerProfile}/approve', [SellerReviewController::class, 'approve'])->name('sellers.approve');
        Route::get('/products/review', [ProductReviewController::class, 'index'])->name('products.review');
        Route::post('/products/{product}/approve', [ProductReviewController::class, 'approve'])->name('products.approve');
    });
});
