<?php
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MarketplaceProductController;
use App\Http\Controllers\SellerApplicationController;
use App\Http\Controllers\SellerProductController;
use App\Http\Controllers\SellerCouponController;
use App\Http\Controllers\Admin\ProductReviewController;
use App\Http\Controllers\Admin\SellerReviewController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\SellerStorefrontController;
use App\Http\Controllers\SellerFollowController;
use App\Http\Controllers\SitemapController;
use App\Http\Controllers\WishlistController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\DownloadController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\StripeWebhookController;
use App\Http\Controllers\SellerFinanceController;
use App\Http\Controllers\StripeConnectController;
use App\Http\Controllers\WithdrawalController;
use App\Http\Controllers\Admin\WithdrawalReviewController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\SupportTicketController;
use App\Http\Controllers\RefundRequestController;
use App\Http\Controllers\DisputeController;
use App\Http\Controllers\Admin\DisputeReviewController;
use App\Http\Controllers\NotificationPreferenceController;
use App\Http\Controllers\Admin\RefundReviewController;
use App\Http\Controllers\Admin\OperationsDashboardController;
use App\Http\Controllers\Admin\UserDirectoryController;
use App\Http\Controllers\Admin\OrderDirectoryController;
use App\Http\Controllers\Admin\AuditLogController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\PageController as AdminPageController;
use App\Http\Controllers\Admin\SupportManagementController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\Admin\BlogPostController;
use App\Http\Controllers\Admin\MenuItemController;
use App\Http\Controllers\Admin\SystemHealthController;
use App\Http\Controllers\Admin\CouponController;
use App\Http\Controllers\InstallController;
use Illuminate\Support\Facades\Route;
Route::get('/install', [InstallController::class, 'show'])->name('install.show');
Route::post('/install', [InstallController::class, 'store'])->middleware('throttle:6,1')->name('install.store');
Route::get('/', HomeController::class)->name('home');
Route::get('/products', [MarketplaceProductController::class, 'index'])->name('products.index');
Route::get('/products/{slug}', [MarketplaceProductController::class, 'show'])->name('products.show');
Route::get('/categories/{slug}', [CategoryController::class, 'show'])->name('categories.show');
Route::get('/authors/{username}', [SellerStorefrontController::class, 'show'])->name('sellers.show');
Route::get('/sitemap.xml', SitemapController::class)->name('sitemap');
Route::get('/pages/{slug}', [PageController::class, 'show'])->name('pages.show');
Route::get('/blog', [BlogController::class, 'index'])->name('blog.index');
Route::get('/blog/{slug}', [BlogController::class, 'show'])->name('blog.show');
Route::post('/stripe/webhook', StripeWebhookController::class)->name('stripe.webhook');
Route::middleware('guest')->group(function () {
    Route::view('/login', 'auth.login')->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store'])->middleware('throttle:login')->name('login.store');
    Route::get('/register', function () {
        if (! \App\Models\Setting::enabled('features.registration')) {
            return redirect()->route('login')->with('registration_closed', true);
        }
        return view('auth.register');
    })->name('register');
    Route::post('/register', [RegisteredUserController::class, 'store'])->middleware('throttle:6,1')->name('register.store');
});
Route::middleware('auth')->group(function () {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
    Route::get('/admin', OperationsDashboardController::class)->middleware('role:administrator')->name('admin.dashboard');
    Route::get('/wishlist', [WishlistController::class, 'index'])->name('wishlist.index');
    Route::post('/wishlist/{product}', [WishlistController::class, 'toggle'])->name('wishlist.toggle');
    Route::post('/authors/{sellerProfile}/follow', [SellerFollowController::class, 'toggle'])->name('sellers.follow');
    Route::get('/cart', [CartController::class, 'index'])->name('cart.index');
    Route::post('/cart/coupon', [CartController::class, 'applyCoupon'])->middleware('throttle:10,1')->name('cart.coupon.apply');
    Route::delete('/cart/coupon', [CartController::class, 'removeCoupon'])->name('cart.coupon.remove');
    Route::post('/cart/{product}', [CartController::class, 'add'])->name('cart.add');
    Route::delete('/cart/items/{item}', [CartController::class, 'remove'])->name('cart.remove');
    Route::post('/checkout', [CheckoutController::class, 'store'])->name('checkout.store');
    Route::get('/checkout/{order}/success', [CheckoutController::class, 'success'])->name('checkout.success');
    Route::get('/purchases', [PurchaseController::class, 'index'])->name('purchases.index');
    Route::get('/purchases/{order}', [PurchaseController::class, 'show'])->name('purchases.show');
    Route::get('/downloads/{license}', DownloadController::class)->name('downloads.show');
    Route::post('/reviews/{orderItem}', [ReviewController::class, 'store'])->name('reviews.store');
    Route::post('/products/{product}/comments', [CommentController::class, 'store'])->name('comments.store');
    Route::get('/support', [SupportTicketController::class, 'index'])->name('support.index');
    Route::post('/support/{license}', [SupportTicketController::class, 'store'])->name('support.store');
    Route::get('/support/{supportTicket}', [SupportTicketController::class, 'show'])->name('support.show');
    Route::post('/support/{supportTicket}/reply', [SupportTicketController::class, 'reply'])->name('support.reply');
    Route::post('/refunds/{orderItem}', [RefundRequestController::class, 'store'])->name('refunds.store');
    Route::post('/disputes/{orderItem}', [DisputeController::class, 'store'])->name('disputes.store');
    Route::get('/affiliates', [\App\Http\Controllers\AffiliateController::class, 'show'])->name('affiliates.show');
    Route::post('/affiliates', [\App\Http\Controllers\AffiliateController::class, 'store'])->name('affiliates.store');
    Route::get('/notification-preferences', [NotificationPreferenceController::class, 'edit'])->name('notifications.preferences');
    Route::put('/notification-preferences', [NotificationPreferenceController::class, 'update'])->name('notifications.preferences.update');
    Route::get('/sell/apply', [SellerApplicationController::class, 'create'])->name('seller.apply');
    Route::post('/sell/apply', [SellerApplicationController::class, 'store'])->name('seller.apply.store');
    Route::middleware('role:seller')->prefix('seller')->name('seller.')->group(function () {
        Route::get('/', \App\Http\Controllers\SellerDashboardController::class)->name('dashboard');
        Route::get('/sales', \App\Http\Controllers\SellerSalesController::class)->name('sales');
        Route::get('/customers', \App\Http\Controllers\SellerCustomerController::class)->name('customers');
        Route::get('/finance', SellerFinanceController::class)->name('finance');
        Route::post('/withdrawals', [WithdrawalController::class, 'store'])->name('withdrawals.store');
        Route::put('/payout-settings', [\App\Http\Controllers\SellerPayoutSettingsController::class, 'update'])->name('payout-settings.update');
        Route::get('/stripe-connect', [StripeConnectController::class, 'start'])->name('connect.start');
        Route::get('/stripe-connect/return', [StripeConnectController::class, 'returned'])->name('connect.return');
        Route::get('/stripe-connect/refresh', [StripeConnectController::class, 'refresh'])->name('connect.refresh');
        Route::get('/products', [SellerProductController::class, 'index'])->name('products.index');
        Route::get('/products/create', [SellerProductController::class, 'create'])->name('products.create');
        Route::post('/products', [SellerProductController::class, 'store'])->name('products.store');
        Route::post('/products/{product}/submit', [SellerProductController::class, 'submit'])->name('products.submit');
        Route::get('/products/{product}/edit', [SellerProductController::class, 'edit'])->name('products.edit');
        Route::put('/products/{product}', [SellerProductController::class, 'update'])->name('products.update');
        Route::post('/products/{product}/versions', [SellerProductController::class, 'storeVersion'])->name('products.versions.store');
        Route::post('/products/{product}/images', [SellerProductController::class, 'storeImages'])->name('products.images.store');
        Route::delete('/products/{product}/images/{image}', [SellerProductController::class, 'destroyImage'])->name('products.images.destroy');
        Route::get('/coupons', [SellerCouponController::class, 'index'])->name('coupons.index');
        Route::post('/coupons', [SellerCouponController::class, 'store'])->name('coupons.store');
        Route::put('/coupons/{coupon}/toggle', [SellerCouponController::class, 'toggle'])->name('coupons.toggle');
        Route::delete('/coupons/{coupon}', [SellerCouponController::class, 'destroy'])->name('coupons.destroy');
    });
    Route::middleware('role:administrator')->prefix('admin')->name('admin.')->group(function () {
        Route::get('/withdrawals', [WithdrawalReviewController::class, 'index'])->name('withdrawals.index');
        Route::post('/withdrawals/{withdrawalRequest}/approve', [WithdrawalReviewController::class, 'approve'])->name('withdrawals.approve');
        Route::post('/withdrawals/{withdrawalRequest}/mark-paid', [WithdrawalReviewController::class, 'markPaid'])->name('withdrawals.mark-paid');
        Route::post('/withdrawals/{withdrawalRequest}/reject', [WithdrawalReviewController::class, 'reject'])->name('withdrawals.reject');
        Route::get('/refunds', [RefundReviewController::class, 'index'])->name('refunds.index');
        Route::post('/refunds/{refundRequest}/approve', [RefundReviewController::class, 'approve'])->name('refunds.approve');
        Route::post('/refunds/{refundRequest}/reject', [RefundReviewController::class, 'reject'])->name('refunds.reject');
        Route::get('/sellers', [SellerReviewController::class, 'index'])->name('sellers.index');
        Route::post('/sellers/{sellerProfile}/approve', [SellerReviewController::class, 'approve'])->name('sellers.approve');
        Route::post('/sellers/{sellerProfile}/reject', [SellerReviewController::class, 'reject'])->name('sellers.reject');
        Route::put('/sellers/{sellerProfile}/feature', [SellerReviewController::class, 'feature'])->name('sellers.feature');
        Route::get('/products', [\App\Http\Controllers\Admin\ProductDirectoryController::class, 'index'])->name('products.index');
        Route::get('/products/review', [ProductReviewController::class, 'index'])->name('products.review');
        Route::post('/products/{product}/approve', [ProductReviewController::class, 'approve'])->name('products.approve');
        Route::post('/products/{product}/request-changes', [ProductReviewController::class, 'requestChanges'])->name('products.request-changes');
        Route::post('/versions/{version}/approve', [ProductReviewController::class, 'approveVersion'])->name('versions.approve');
        Route::post('/versions/{version}/reject', [ProductReviewController::class, 'rejectVersion'])->name('versions.reject');
        Route::get('/users', [UserDirectoryController::class, 'index'])->name('users.index');
        Route::put('/users/{user}/status', [UserDirectoryController::class, 'updateStatus'])->name('users.status');
        Route::get('/orders', [OrderDirectoryController::class, 'index'])->name('orders.index');
        Route::get('/orders/export', [OrderDirectoryController::class, 'export'])->name('orders.export');
        Route::get('/disputes', [DisputeReviewController::class, 'index'])->name('disputes.index');
        Route::post('/disputes/{dispute}/uphold', [DisputeReviewController::class, 'uphold'])->name('disputes.uphold');
        Route::post('/disputes/{dispute}/dismiss', [DisputeReviewController::class, 'dismiss'])->name('disputes.dismiss');
        Route::get('/audits', [AuditLogController::class, 'index'])->name('audits.index');
        Route::get('/audits/export', [AuditLogController::class, 'export'])->name('audits.export');
        Route::get('/support', [SupportManagementController::class, 'index'])->name('support.index');
        Route::get('/support/{supportTicket}', [SupportManagementController::class, 'show'])->name('support.show');
        Route::post('/support/{supportTicket}/reply', [SupportManagementController::class, 'reply'])->name('support.reply');
        Route::put('/support/{supportTicket}/status', [SupportManagementController::class, 'updateStatus'])->name('support.status');
        Route::get('/settings', [SettingController::class, 'index'])->name('settings.index');
        Route::put('/settings', [SettingController::class, 'update'])->name('settings.update');
        Route::post('/settings/sections/{section}', [SettingController::class, 'updateSection'])->name('settings.sections.update');
        Route::post('/settings/branding', [SettingController::class, 'updateBranding'])->name('settings.branding.update');
        Route::get('/categories', [\App\Http\Controllers\Admin\CategoryController::class, 'index'])->name('categories.index');
        Route::post('/categories', [\App\Http\Controllers\Admin\CategoryController::class, 'store'])->name('categories.store');
        Route::put('/categories/{category}', [\App\Http\Controllers\Admin\CategoryController::class, 'update'])->name('categories.update');
        Route::delete('/categories/{category}/image', [\App\Http\Controllers\Admin\CategoryController::class, 'removeImage'])->name('categories.image.remove');
        Route::put('/categories/{category}/toggle', [\App\Http\Controllers\Admin\CategoryController::class, 'toggle'])->name('categories.toggle');
        Route::delete('/categories/{category}', [\App\Http\Controllers\Admin\CategoryController::class, 'destroy'])->name('categories.destroy');
        Route::get('/pages', [AdminPageController::class, 'index'])->name('pages.index');
        Route::get('/pages/create', [AdminPageController::class, 'create'])->name('pages.create');
        Route::post('/pages', [AdminPageController::class, 'store'])->name('pages.store');
        Route::get('/pages/{page}/edit', [AdminPageController::class, 'edit'])->name('pages.edit');
        Route::put('/pages/{page}', [AdminPageController::class, 'update'])->name('pages.update');
        Route::get('/blog', [BlogPostController::class, 'index'])->name('blog.index');
        Route::get('/blog/create', [BlogPostController::class, 'create'])->name('blog.create');
        Route::post('/blog', [BlogPostController::class, 'store'])->name('blog.store');
        Route::get('/blog/{post}/edit', [BlogPostController::class, 'edit'])->name('blog.edit');
        Route::put('/blog/{post}', [BlogPostController::class, 'update'])->name('blog.update');
        Route::get('/menus', [MenuItemController::class, 'index'])->name('menus.index');
        Route::post('/menus', [MenuItemController::class, 'store'])->name('menus.store');
        Route::put('/menus/{menuItem}', [MenuItemController::class, 'update'])->name('menus.update');
        Route::delete('/menus/{menuItem}', [MenuItemController::class, 'destroy'])->name('menus.destroy');
        Route::get('/coupons', [CouponController::class, 'index'])->name('coupons.index');
        Route::post('/coupons', [CouponController::class, 'store'])->name('coupons.store');
        Route::put('/coupons/{coupon}/toggle', [CouponController::class, 'toggle'])->name('coupons.toggle');
        Route::delete('/coupons/{coupon}', [CouponController::class, 'destroy'])->name('coupons.destroy');
        Route::get('/system', [SystemHealthController::class, 'index'])->name('system');
        Route::post('/system/backup', [SystemHealthController::class, 'backup'])->name('system.backup');
    });
});
