<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('license_types',function(Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->text('description');$t->boolean('allows_paid_end_product')->default(false);$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('carts',function(Blueprint $t){$t->id();$t->foreignId('user_id')->unique()->constrained()->cascadeOnDelete();$t->string('currency',3)->default('USD');$t->timestamps();});
  Schema::create('cart_items',function(Blueprint $t){$t->id();$t->foreignId('cart_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->foreignId('license_type_id')->constrained()->restrictOnDelete();$t->decimal('unit_price',12,2);$t->decimal('tax',12,2)->default(0);$t->decimal('discount',12,2)->default(0);$t->decimal('total',12,2);$t->timestamps();$t->unique(['cart_id','product_id']);});
  Schema::create('orders',function(Blueprint $t){$t->id();$t->string('number')->unique();$t->foreignId('user_id')->constrained()->restrictOnDelete();$t->string('currency',3);$t->decimal('subtotal',12,2);$t->decimal('discount',12,2)->default(0);$t->decimal('tax',12,2)->default(0);$t->decimal('fees',12,2)->default(0);$t->decimal('total',12,2);$t->string('payment_status',24)->default('pending')->index();$t->string('status',24)->default('awaiting_payment')->index();$t->string('stripe_checkout_session_id')->nullable()->unique();$t->string('customer_ip',45)->nullable();$t->text('user_agent')->nullable();$t->timestamp('paid_at')->nullable();$t->timestamps();});
  Schema::create('order_items',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained()->restrictOnDelete();$t->foreignId('seller_id')->constrained('users')->restrictOnDelete();$t->foreignId('product_version_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('license_type_id')->constrained()->restrictOnDelete();$t->string('product_title');$t->string('seller_name');$t->string('license_name');$t->decimal('unit_price',12,2);$t->decimal('discount',12,2)->default(0);$t->decimal('tax',12,2)->default(0);$t->decimal('platform_commission',12,2)->default(0);$t->decimal('seller_earning',12,2)->default(0);$t->decimal('total',12,2);$t->timestamps();});
  Schema::create('payments',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->restrictOnDelete();$t->string('provider')->default('stripe');$t->string('provider_payment_id')->unique();$t->decimal('amount',12,2);$t->string('currency',3);$t->string('status',24)->index();$t->json('payload')->nullable();$t->timestamp('paid_at')->nullable();$t->timestamps();});
  Schema::create('stripe_webhook_events',function(Blueprint $t){$t->id();$t->string('stripe_event_id')->unique();$t->string('event_type')->index();$t->json('payload');$t->string('processing_status',24)->default('pending')->index();$t->timestamp('processed_at')->nullable();$t->text('error_message')->nullable();$t->unsignedInteger('retry_count')->default(0);$t->timestamps();});
  Schema::create('licenses',function(Blueprint $t){$t->id();$t->string('license_key')->unique();$t->foreignId('product_id')->constrained()->restrictOnDelete();$t->foreignId('product_version_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('user_id')->constrained()->restrictOnDelete();$t->foreignId('order_item_id')->unique()->constrained()->restrictOnDelete();$t->foreignId('license_type_id')->constrained()->restrictOnDelete();$t->string('status',24)->default('active')->index();$t->unsignedInteger('activation_limit')->default(1);$t->unsignedInteger('activation_count')->default(0);$t->timestamp('support_expires_at')->nullable();$t->timestamps();});
  Schema::create('downloads',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->restrictOnDelete();$t->foreignId('product_id')->constrained()->restrictOnDelete();$t->foreignId('product_version_id')->constrained()->restrictOnDelete();$t->foreignId('order_id')->constrained()->restrictOnDelete();$t->foreignId('license_id')->constrained()->restrictOnDelete();$t->string('ip_address',45)->nullable();$t->text('user_agent')->nullable();$t->timestamp('downloaded_at');$t->timestamps();$t->index(['license_id','downloaded_at']);});
 }
 public function down(): void {foreach(['downloads','licenses','stripe_webhook_events','payments','order_items','orders','cart_items','carts','license_types'] as $table)Schema::dropIfExists($table);}
};