<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void{
  Schema::create('seller_wallets',function(Blueprint $t){$t->id();$t->foreignId('seller_id')->constrained('users')->restrictOnDelete();$t->string('currency',3);$t->decimal('pending_balance',14,2)->default(0);$t->decimal('available_balance',14,2)->default(0);$t->decimal('reserved_balance',14,2)->default(0);$t->decimal('withdrawn_balance',14,2)->default(0);$t->decimal('lifetime_earnings',14,2)->default(0);$t->timestamps();$t->unique(['seller_id','currency']);});
  Schema::create('wallet_transactions',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('seller_wallet_id')->constrained()->restrictOnDelete();$t->foreignId('order_item_id')->nullable()->constrained()->restrictOnDelete();$t->string('type',40)->index();$t->string('balance_bucket',24);$t->decimal('amount',14,2);$t->string('currency',3);$t->string('reference')->unique();$t->timestamp('available_at')->nullable()->index();$t->timestamp('cleared_at')->nullable();$t->json('metadata')->nullable();$t->timestamp('created_at')->useCurrent();});
  Schema::create('commission_rules',function(Blueprint $t){$t->id();$t->string('scope_type',24)->index();$t->unsignedBigInteger('scope_id')->nullable()->index();$t->decimal('rate',5,2);$t->decimal('fixed_fee',12,2)->default(0);$t->unsignedInteger('priority')->default(0);$t->boolean('is_active')->default(true);$t->timestamp('starts_at')->nullable();$t->timestamp('ends_at')->nullable();$t->timestamps();$t->index(['scope_type','scope_id','is_active']);});
  Schema::create('withdrawal_requests',function(Blueprint $t){$t->id();$t->string('number')->unique();$t->foreignId('seller_id')->constrained('users')->restrictOnDelete();$t->foreignId('seller_wallet_id')->constrained()->restrictOnDelete();$t->decimal('amount',14,2);$t->decimal('fee',14,2)->default(0);$t->decimal('net_amount',14,2);$t->string('status',24)->default('pending')->index();$t->text('administrator_note')->nullable();$t->string('stripe_transfer_id')->nullable()->unique();$t->string('stripe_payout_id')->nullable();$t->timestamp('processed_at')->nullable();$t->timestamps();});
  Schema::create('stripe_connected_accounts',function(Blueprint $t){$t->id();$t->foreignId('seller_id')->unique()->constrained('users')->cascadeOnDelete();$t->string('stripe_account_id')->unique();$t->string('account_type',24)->default('express');$t->string('status',24)->default('pending')->index();$t->boolean('details_submitted')->default(false);$t->boolean('charges_enabled')->default(false);$t->boolean('payouts_enabled')->default(false);$t->json('requirements')->nullable();$t->timestamp('last_synced_at')->nullable();$t->timestamps();});
 }
 public function down():void{foreach(['stripe_connected_accounts','withdrawal_requests','commission_rules','wallet_transactions','seller_wallets'] as $table)Schema::dropIfExists($table);}
};