<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void{
  Schema::create('reviews',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->restrictOnDelete();$t->foreignId('order_item_id')->unique()->constrained()->restrictOnDelete();$t->unsignedTinyInteger('rating');$t->string('title');$t->text('content');$t->string('status',24)->default('approved')->index();$t->text('seller_response')->nullable();$t->unsignedInteger('helpful_votes')->default(0);$t->timestamps();$t->unique(['product_id','user_id']);});
  Schema::create('comments',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->restrictOnDelete();$t->foreignId('parent_id')->nullable()->constrained('comments')->cascadeOnDelete();$t->text('content');$t->string('status',24)->default('approved')->index();$t->boolean('is_pinned')->default(false);$t->boolean('is_seller_answer')->default(false);$t->timestamps();});
  Schema::create('support_tickets',function(Blueprint $t){$t->id();$t->string('number')->unique();$t->foreignId('user_id')->constrained()->restrictOnDelete();$t->foreignId('seller_id')->constrained('users')->restrictOnDelete();$t->foreignId('product_id')->constrained()->restrictOnDelete();$t->foreignId('order_id')->constrained()->restrictOnDelete();$t->foreignId('license_id')->constrained()->restrictOnDelete();$t->string('subject');$t->string('priority',16)->default('normal');$t->string('status',24)->default('open')->index();$t->timestamp('first_response_at')->nullable();$t->timestamp('resolved_at')->nullable();$t->timestamps();});
  Schema::create('support_messages',function(Blueprint $t){$t->id();$t->foreignId('support_ticket_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->restrictOnDelete();$t->text('message');$t->boolean('is_internal')->default(false);$t->timestamps();});
  Schema::create('refund_requests',function(Blueprint $t){$t->id();$t->string('number')->unique();$t->foreignId('user_id')->constrained()->restrictOnDelete();$t->foreignId('order_id')->constrained()->restrictOnDelete();$t->foreignId('order_item_id')->unique()->constrained()->restrictOnDelete();$t->foreignId('product_id')->constrained()->restrictOnDelete();$t->foreignId('seller_id')->constrained('users')->restrictOnDelete();$t->string('reason');$t->text('description');$t->decimal('requested_amount',12,2);$t->decimal('approved_amount',12,2)->nullable();$t->string('status',32)->default('submitted')->index();$t->text('seller_response')->nullable();$t->text('administrator_decision')->nullable();$t->timestamp('decided_at')->nullable();$t->timestamps();});
  Schema::create('notification_preferences',function(Blueprint $t){$t->id();$t->foreignId('user_id')->unique()->constrained()->cascadeOnDelete();$t->boolean('email_sales')->default(true);$t->boolean('email_product_updates')->default(true);$t->boolean('email_support')->default(true);$t->boolean('email_marketing')->default(false);$t->boolean('in_app')->default(true);$t->timestamps();});
 }
 public function down():void{foreach(['notification_preferences','refund_requests','support_messages','support_tickets','comments','reviews'] as $table)Schema::dropIfExists($table);}
};